language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: e5a53a0d9cd19cf435d6446a21a908273d9a9e6f
  local_dir: dist
  on:
    branch: master